# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "AppleSiliconDDC" = "sha256-qs3droVRU0R5EdrgjUBXui59cziQgS2eqUOTcaDC9F4=";
    "swift-argument-parser" = "sha256-90ECc3iEmxvOUk9iLKbQdQEz88dOisPqWsJLOFcKUV8=";
    "swift-log" = "sha256-MW9QSZrCdX/D7w02pOwBn4SnWP5DJ+GXJUr5/XN5Ch8=";
  };
}
