# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-argument-parser" = "sha256-MzJmBxWztP8ut4VA6INBVIVxE77OpCPcNqBRM9ujb7k=";
    "swift-log" = "sha256-MW9QSZrCdX/D7w02pOwBn4SnWP5DJ+GXJUr5/XN5Ch8=";
  };
}
