---
name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Check flake.lock
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: sestrella
          extraPullNames: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build configuration
        run: nix run home-manager/release-24.11 -- build --flake ${{ github.workspace }}
