---
name: build

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v8
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://devenv.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
      - name: Build configuration
        run: nix run home-manager/release-23.11 -- build --flake ${{ github.workspace }}
        timeout-minutes: 2
      - name: Activate the configuration
        run: ./result/activate
