---
name: build

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: sestrella
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: devenv
      - name: Build and activate configuration
        run: nix run home-manager/release-23.11 -- switch --flake ${{ github.workspace }} -b bak
