---
name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Run tests
        run: devenv test

  build:
    runs-on: macos-latest
    needs: [check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: sestrella
          extraPullNames: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build configuration
        run: nix run home-manager/master -- build --flake ${{ github.workspace }}
