---
name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix build .#darwinConfigurations.ci.system
      # FIXME: error: Directory /run does not exist, aborting activation
      # - run: ./result/sw/bin/darwin-rebuild switch --flake .#ci
