name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  devenv-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix profile add nixpkgs#devenv
      - run: devenv test

  devenv-build:
    needs: [devenv-test]
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: sestrella
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix profile add nixpkgs#devenv
      - run: echo '{ cachix.push = "sestrella"; }' > devenv.local.nix
      - run: devenv build
    
  hm-build:
    needs: [devenv-test]
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: accept-flake-config = true
      - uses: cachix/cachix-action@v17
        with:
          name: sestrella
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run home-manager/master -- build --flake .
