---
name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - run: sudo scutil --set HostName ghactions
      - run: printf 'run\tprivate/var/run\n' | sudo tee -a /etc/synthetic.conf
      - run: nix build .#darwinConfigurations."ghactions".system
      - run: ./result/sw/bin/darwin-rebuild switch --flake .
