---
name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/flake-checker-action@v5
      - uses: DeterminateSystems/nix-installer-action@v6
      - run: nix run home-manager/master -- init --switch
