---
name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - run: nix build .#darwinConfigurations."ghactions".system
      # TODO: Fix issue running darwin-rebuild
      # - run: ./result/sw/bin/darwin-rebuild switch --flake .
