---
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: experimental-features = nix-command flakes
      - run: nix build .#homeConfigurations.sestrella.activationPackage
      - run: ls -al
