---
name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: hostname
      - run: sudo scutil --set HostName ghactions
      - run: hostname
      # - uses: actions/checkout@v3
      # - uses: cachix/install-nix-action@v15
      #   with:
      #     extra_nix_config: experimental-features = nix-command flakes
      # - run: nix build .#homeConfigurations.sestrella.activationPackage
      # - run: ./result/activate
