---
name: CI

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v8
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Build and activate configuration
        run: nix run home-manager/release-24.05 -- switch --flake ${{ github.workspace }} -b bak
        timeout-minutes: 5
