---
name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ~/.config/nixpkgs
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-env -f '<nixpkgs>' -i home-manager
      - run: home-manager switch -f home.nix
