---
name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable:home-manager=channel:home-manager
      - run: nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
      - run: nix-channel --update
      - run: nix-shell '<home-manager>' -A install
      # - run: ln -s $PWD ~/.config/nixpkgs
      # - run: home-manager switch
