---
name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix build .#ci
      # TODO: Fix issue running darwin-rebuild
      # - run: ./result/sw/bin/darwin-rebuild switch --flake .
