---
name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v24
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv
      - run: cat /etc/nix/nix.conf
      - run: cat ~/.config/nix/nix.conf
      - name: Build configuration
        run: nix run home-manager/release-23.11 -- build --flake ${{ github.workspace }}
        timeout-minutes: 2
      - name: Activate the configuration
        run: ./result/activate
