---
name: CI

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "experimental-features = nix-command flakes"
      - run: ln -s $PWD ~/.config/nixpkgs
      - run: ls -al ~/.config/nixpkgs
      - run: sed -i '' 's/sestrella/runner/g' flake.nix
      - run: nix-shell --run 'home-manager switch'
