---
name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v8
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Build configuration
        run: nix run home-manager/release-24.05 -- build --flake ${{ github.workspace }}
