---
name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-channel --add https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager
      - run: nix-channel --update
      - run: nix-shell '<home-manager>' -A install
      - run: home-manager switch
