name: Templates

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        template:
          - templates/import-module
      fail-fast: false
    defaults:
      run:
        working-directory: ${{ matrix.template }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            max-jobs = 0
      - run: pwd
      - run: ls -al
      - run: nix run home-manager/master -- build --flake .
