name: Templates

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/templates.yml
      - flake.*
      - home.nix
      - home/**
      - packages/**
      - templates/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/templates.yml
      - flake.*
      - home.nix
      - home/**
      - packages/**
      - templates/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        template:
          - templates/default
      fail-fast: false
    runs-on: macos-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ${{ matrix.template }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: accept-flake-config = true
      - run: sed -i 's/github:sestrella\/home-manager\.config/github:sestrella\/home-manager\.config?ref=${{ github.sha }}/' flake.nix
      - name: Build template
        run: nix run . -- build --flake .
